# Generated by Django 3.2.5 on 2021-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
