# Generated by Django 3.2.5 on 2021-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_project_project_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/project'),
        ),
    ]
